git clone https://github.com/vim-airline/vim-airline.git;
git clone https://github.com/scrooloose/syntastic.git;
git clone https://github.com/scrooloose/nerdtree.git;
git clone https://github.com/majutsushi/tagbar.git;
git clone https://github.com/Shutnik/jshint2.vim.git;
git clone https://github.com/nvie/vim-flake8.git;
git clone https://github.com/nathanaelkane/vim-indent-guides.git;
git clone https://github.com/tpope/vim-surround.git;
git clone https://github.com/tpope/vim-rails.git;
git clone https://github.com/vim-ruby/vim-ruby.git;
git clone https://github.com/airblade/vim-gitgutter.git;
git clone https://github.com/vim-airline/vim-airline-themes.git;
git clone https://github.com/leafgarland/typescript-vim.git;
git clone https://github.com/HerringtonDarkholme/yats.vim.git
git clone https://github.com/tpope/vim-fugitive.git
git clone https://github.com/ngmy/vim-rubocop.git
git clone https://github.com/kien/ctrlp.vim.git
git clone https://github.com/kchmck/vim-coffee-script.git
